config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/index' => 'users#index'
  get '/photos/index/:id' => 'photos#index', as: 'photo_link'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @user = User.joins(:photos)
    @photos = Photo.joins(:comments)


    @user = User.find(params[:id])
    @photos = @user.photos


  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users_all = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<h1>PhotoSite Photo List</h1>

<p>Showing photos of <%= @user.first_name%>
                      <%= @user.last_name%></p>

<style>
  table, th, tr, td {
    border: 1px solid black;
  }
</style>

<table>
  <col width="400">
  <col width="200">
  <col width="400">
  <tr>
    <th>Photo</th>
    <th>Creation Time</th>
    <th>Comment</th>
  </tr>
  <% @photos.each do |photo|%>
    <tr>
      <td><%= image_tag(photo.file_name)%></td>
      <td>Create at <br/><%= photo.date_time%></td>
      <td>
        <%@comment = photo.comments%>
        <% @comment.each do |comment|%>
              <p><b>Post On:</b> <%= comment.date_time%><br/></p>
              <p><b>Post By:</b> <%= link_to comment.user.first_name, photo_link_path(comment.user.id)%>
                                 <%= link_to comment.user.last_name, photo_link_path(comment.user.id)%>
              </p>
              <p><%= comment.comment_text%></p>
        <% end %>

      </td>
    </tr>
  <% end %>

</table>

app/views/user/index.html.erb
<h1>PhotoSite User List</h1>

There are 6 users

<table>
  <tr>
    <th>User</th>
    <th>FirstName</th>
    <th>LastName</th>
  </tr>
  <% User.all.each do |user| %>
      <tr>
        <td><%= link_to user.id, photo_link_path(user.id) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>

      </tr>
  <% end %>

</table>

app/views/users/index.html.erb
<h1>PhotoSite User List</h1>

<p>There are <%=User.count%> users</p>

<table>
  <tr>
    <th>User</th>
    <th>FirstName</th>
    <th>LastName</th>
  </tr>
  <% User.all.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.first_name, photo_link_path(user.id)%></td>
        <td><%= link_to user.last_name, photo_link_path(user.id) %></td>

      </tr>
  <% end %>

</table>